// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/japhy-tech/backend-test/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// BreedsCRUD is an autogenerated mock type for the BreedsCRUD type
type BreedsCRUD struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, breeds
func (_m *BreedsCRUD) Create(ctx context.Context, breeds entity.Breeds) error {
	ret := _m.Called(ctx, breeds)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Breeds) error); ok {
		r0 = rf(ctx, breeds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BreedsCRUD) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: ctx, filtername, input
func (_m *BreedsCRUD) Read(ctx context.Context, filtername string, input string) ([]entity.Breeds, error) {
	ret := _m.Called(ctx, filtername, input)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []entity.Breeds
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Breeds, error)); ok {
		return rf(ctx, filtername, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []entity.Breeds); ok {
		r0 = rf(ctx, filtername, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Breeds)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, filtername, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, breeds
func (_m *BreedsCRUD) Update(ctx context.Context, breeds entity.Breeds) error {
	ret := _m.Called(ctx, breeds)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Breeds) error); ok {
		r0 = rf(ctx, breeds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBreedsCRUD creates a new instance of BreedsCRUD. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBreedsCRUD(t interface {
	mock.TestingT
	Cleanup(func())
}) *BreedsCRUD {
	mock := &BreedsCRUD{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
